[project]
name = "nokhodkhor"
version = "0.1.0"
description = "Pac-Man inspired game in pygame"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
